import type { Config } from "tailwindcss";

const config: Config = {
	content: [
		"./pages/**/*.{js,ts,jsx,tsx,mdx}",
		"./components/**/*.{js,ts,jsx,tsx,mdx}",
		"./app/**/*.{js,ts,jsx,tsx,mdx}",
		"./src/**/*.{js,ts,jsx,tsx}",
	],
	theme: {
		fontFamily: {
			CamptonThin: ["Campton-Thin"],
			CamptonThinItalic: ["Campton-ThinItalic"],
			CamptonExtraLight: ["Campton-ExtraLight"],
			CamptonExtraLightItalic: ["Campton-ExtraLightItalic"],
			CamptonLight: ["Campton-Light"],
			CamptonLightItalic: ["Campton-LightItalic"],
			CamptonBook: ["Campton-Book"],
			CamptonBookItalic: ["Campton-BookItalic"],
			CamptonMedium: ["Campton-Medium"],
			CamptonMediumItalic: ["Campton-MediumItalic"],
			CamptonSemiBold: ["Campton-SemiBold"],
			CamptonSemiBoldItalic: ["Campton-SemiBoldItalic"],
			CamptonBold: ["Campton-Bold"],
			CamptonBoldItalic: ["Campton-BoldItalic"],
			CamptonExtraBold: ["Campton-ExtraBold"],
			CamptonExtraBoldItalic: ["Campton-ExtraBoldItalic"],
			CamptonBlack: ["Campton-Black"],
			CamptonBlackItalic: ["Campton-BlackItalic"],
			LarsseitThin: ["Larsseit-Thin"],
			LarsseitThinItalic: ["Larsseit-ThinItalic"],
			LarsseitLight: ["Larsseit-Light"],
			LarsseitLightItalic: ["Larsseit-LightItalic"],
			LarsseitMedium: ["Larsseit-Medium"],
			LarsseitMediumItalic: ["Larsseit-MediumItalic"],
			LarsseitBold: ["Larsseit-Bold"],
			LarsseitBoldItalic: ["Larsseit-BoldItalic"],
			LarsseitExtraBold: ["Larsseit-ExtraBold"],
			LarsseitExtraBoldItalic: ["Larsseit-ExtraBoldItalic"],
			QuincyThin: ["Quincy-Thin"],
			QuincyThinItalic: ["Quincy-ThinItalic"],
			QuincyLight: ["Quincy-Light"],
			QuincyLightItalic: ["Quincy-LightItalic"],
			QuincyText: ["Quincy-Text"],
			QuincyTextItalic: ["Quincy-TextItalic"],
			QuincyMedium: ["Quincy-Medium"],
			QuincyMediumItalic: ["Quincy-MediumItalic"],
			QuincyRegular: ["Quincy-Regular"],
			QuincyRegularItalic: ["Quincy-RegularItalic"],
			QuincyBold: ["Quincy-Bold"],
			QuincyBoldItalic: ["Quincy-BoldItalic"],
			QuincyExtraBold: ["Quincy-ExtraBold"],
			QuincyExtraBoldItalic: ["Quincy-ExtraBoldItalic"],
			QuincyBlack: ["Quincy-Black"],
			QuincyBlackItalic: ["Quincy-BlackItalic"],
		},
	},
	plugins: [require("daisyui")],
	daisyui: {
		themes: ["light"],
	},
};
export default config;
